version: '3.7'

volumes:
  data-volume:
    driver: local
    driver_opts:
      type: none
      device: /tmp/zencrepes-data
      o: bind

networks:
  zc_stack:
    driver: bridge

services:
  redis:
    container_name: zc_redis
    image: redis:latest
    networks:
      - zc_stack

  keycloak:
    container_name: zc_keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - '8080:8080'
    environment:
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=admin'
    networks:
      - zc_stack

  elasticsearch:
    container_name: zc_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    networks:
      - zc_stack

  # Kibana is only present there for debugging to provide a quick way to look at the data
  kibana:
    container_name: zc_kibana
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - zc_stack
    depends_on:
      - elasticsearch

  zindexer:
    container_name: zc_zindexer
    image: zencrepes/zindexer:latest
    environment:
      - 'CONFIG_DIR=/root/zencrepes'
    volumes:
      - data-volume:/root/zencrepes
    networks:
      - zc_stack
    depends_on:
      - elasticsearch

  zapi:
    container_name: zc_zapi
    image: zencrepes/zapi:latest
    ports:
      - '3001:3001'
    environment:
      - 'CONFIG_PATH=/root/zencrepes'
      - 'KEYCLOAK_DISABLED=false'
      - 'KEYCLOAK_ROLE=zencrepes-data'
      - 'KEYCLOAK_AUTH_SERVER_URL=http://zc_keycloak:8080/auth/'
    volumes:
      - data-volume:/root/zencrepes
    networks:
      - zc_stack
    depends_on:
      - elasticsearch

  zqueue:
    container_name: zc_zqueue
    image: zencrepes/zqueue:latest
    ports:
      - '3003:3003'
    environment:
      - 'CONFIG_PATH=/root/zencrepes'
    volumes:
      - data-volume:/root/zencrepes
    networks:
      - zc_stack
    depends_on:
      - elasticsearch
      - redis

  zui:
    container_name: zc_zui
    image: zencrepes/zui:latest
    environment:
      - 'API_URL=http://localhost:3001/graphql'
      - 'ROOT_URL=http://localhost:3000'
      - 'KEYCLOAK_DISABLED=false'
      - 'KEYCLOAK_AUTH_SERVER_URL=http://zc_keycloak:8080/auth/'
      - 'KEYCLOAK_AUDIENCE=http://localhost:3000'
      - 'KEYCLOAK_REALM=ZenCrepes'
      - 'KEYCLOAK_CLIENT_ID=zencrepes'
    networks:
      - zc_stack
    ports:
      - '3000:80'
    depends_on:
      - elasticsearch
